# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proxy.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_infoview(object):
    def setupUi(self, infoview : QtWidgets.QTabWidget):
        infoview.setObjectName("infoview")
        infoview.resize(740, 535)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        infoview.setFont(font)
        infoview.setTabPosition(0)
        infoview.setTabShape(QtWidgets.QTabWidget.Rounded)
        infoview.setIconSize(QtCore.QSize(40, 30))


        self.information = QtWidgets.QWidget()
        self.information.setEnabled(True)
        self.information.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.information.setObjectName("information")

        self.widget_left = QtWidgets.QWidget(self.information)
        self.widget_left.setGeometry(QtCore.QRect(20, 30, 331, 431))
        self.widget_left.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_left.setObjectName("widget_left")

        self.label_15 = QtWidgets.QLabel(self.widget_left)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_15.setObjectName("label_15")

        self.username = QtWidgets.QLineEdit(self.widget_left)
        self.username.setGeometry(QtCore.QRect(10, 110, 300, 30))
        self.username.setObjectName("username")
        self.label_16 = QtWidgets.QLabel(self.widget_left)
        self.label_16.setGeometry(QtCore.QRect(10, 140, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.UUID = QtWidgets.QTextBrowser(self.widget_left)
        self.UUID.setGeometry(QtCore.QRect(10, 160, 300, 50))
        self.UUID.setObjectName("UUID")
        self.label_17 = QtWidgets.QLabel(self.widget_left)
        self.label_17.setGeometry(QtCore.QRect(10, 220, 30, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.publickey = QtWidgets.QTextBrowser(self.widget_left)
        self.publickey.setGeometry(QtCore.QRect(10, 240, 300, 50))
        self.publickey.setObjectName("publickey")
        self.reset_btn = QtWidgets.QPushButton(self.widget_left)
        self.reset_btn.setGeometry(QtCore.QRect(90, 320, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reset_btn.setFont(font)
        self.reset_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.reset_btn.setObjectName("reset_btn")
        self.widget_right_3 = QtWidgets.QWidget(self.information)
        self.widget_right_3.setGeometry(QtCore.QRect(350, 30, 351, 431))
        self.widget_right_3.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_right_3.setObjectName("widget_right_3")
        self.label_18 = QtWidgets.QLabel(self.widget_right_3)
        self.label_18.setGeometry(QtCore.QRect(10, 90, 72, 15))
        self.label_18.setObjectName("label_18")
        self.version = QtWidgets.QTextBrowser(self.widget_right_3)
        self.version.setGeometry(QtCore.QRect(10, 110, 261, 31))
        self.version.setObjectName("version")
        self.label_19 = QtWidgets.QLabel(self.widget_right_3)
        self.label_19.setGeometry(QtCore.QRect(10, 150, 72, 15))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget_right_3)
        self.label_20.setGeometry(QtCore.QRect(10, 220, 72, 15))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_right_3)
        self.label_21.setGeometry(QtCore.QRect(10, 280, 72, 15))
        self.label_21.setObjectName("label_21")
        self.author = QtWidgets.QTextBrowser(self.widget_right_3)
        self.author.setGeometry(QtCore.QRect(10, 170, 261, 31))
        self.author.setObjectName("author")
        self.workdirectory = QtWidgets.QTextBrowser(self.widget_right_3)
        self.workdirectory.setGeometry(QtCore.QRect(10, 240, 261, 31))
        self.workdirectory.setObjectName("workdirectory")
        self.otherinfo = QtWidgets.QTextBrowser(self.widget_right_3)
        self.otherinfo.setGeometry(QtCore.QRect(10, 300, 261, 111))
        self.otherinfo.setObjectName("otherinfo")
        self.widget_top = QtWidgets.QWidget(self.information)
        self.widget_top.setGeometry(QtCore.QRect(20, 5, 681, 31))
        self.widget_top.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_top.setObjectName("widget_top")
        self.new_btn = QtWidgets.QPushButton(self.widget_top)
        self.new_btn.setGeometry(QtCore.QRect(0, 0, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.new_btn.setFont(font)
        self.new_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.new_btn.setObjectName("new_btn")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Resources/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoview.addTab(self.information, icon, "")
        self.signature = QtWidgets.QWidget()
        self.signature.setObjectName("signature")
        self.widget_center_2 = QtWidgets.QWidget(self.signature)
        self.widget_center_2.setGeometry(QtCore.QRect(20, 0, 341, 461))
        self.widget_center_2.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_center_2.setObjectName("widget_center_2")
        self.label_8 = QtWidgets.QLabel(self.widget_center_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_center_2)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.signfile = QtWidgets.QTextBrowser(self.widget_center_2)
        self.signfile.setGeometry(QtCore.QRect(9, 169, 301, 41))
        self.signfile.setObjectName("signfile")
        self.label_10 = QtWidgets.QLabel(self.widget_center_2)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.signedfile = QtWidgets.QTextBrowser(self.widget_center_2)
        self.signedfile.setGeometry(QtCore.QRect(9, 249, 301, 41))
        self.signedfile.setObjectName("signedfile")
        self.signer = QtWidgets.QComboBox(self.widget_center_2)
        self.signer.setGeometry(QtCore.QRect(10, 110, 301, 21))
        self.signer.setObjectName("signer")
        self.excu_btn = QtWidgets.QPushButton(self.widget_center_2)
        self.excu_btn.setGeometry(QtCore.QRect(90, 310, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.excu_btn.setFont(font)
        self.excu_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.excu_btn.setObjectName("excu_btn")
        self.openfile_btn = QtWidgets.QPushButton(self.widget_center_2)
        self.openfile_btn.setGeometry(QtCore.QRect(120, 140, 21, 21))
        self.openfile_btn.setStyleSheet("border-color: rgb(240, 255, 255);")
        self.openfile_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Resources/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openfile_btn.setIcon(icon1)
        self.openfile_btn.setIconSize(QtCore.QSize(20, 20))
        self.openfile_btn.setObjectName("openfile_btn")
        self.defyfile_btn = QtWidgets.QPushButton(self.widget_center_2)
        self.defyfile_btn.setGeometry(QtCore.QRect(120, 220, 21, 21))
        self.defyfile_btn.setStyleSheet("border-color: rgb(240, 255, 255);")
        self.defyfile_btn.setText("")
        self.defyfile_btn.setIcon(icon1)
        self.defyfile_btn.setIconSize(QtCore.QSize(20, 20))
        self.defyfile_btn.setObjectName("defyfile_btn")
        self.widget_right_2 = QtWidgets.QWidget(self.signature)
        self.widget_right_2.setGeometry(QtCore.QRect(360, 0, 351, 461))
        self.widget_right_2.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_right_2.setObjectName("widget_right_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_right_2)
        self.textBrowser.setGeometry(QtCore.QRect(70, 70, 211, 271))
        self.textBrowser.setObjectName("textBrowser")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./Resources/signature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoview.addTab(self.signature, icon2, "")
        self.verify = QtWidgets.QWidget()
        self.verify.setObjectName("verify")
        self.widget_center_4 = QtWidgets.QWidget(self.verify)
        self.widget_center_4.setGeometry(QtCore.QRect(20, 0, 341, 461))
        self.widget_center_4.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_center_4.setObjectName("widget_center_4")
        self.label_12 = QtWidgets.QLabel(self.widget_center_4)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.UUID_4 = QtWidgets.QTextBrowser(self.widget_center_4)
        self.UUID_4.setGeometry(QtCore.QRect(10, 120, 300, 50))
        self.UUID_4.setObjectName("UUID_4")
        self.label_13 = QtWidgets.QLabel(self.widget_center_4)
        self.label_13.setGeometry(QtCore.QRect(10, 180, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.publickey_4 = QtWidgets.QTextBrowser(self.widget_center_4)
        self.publickey_4.setGeometry(QtCore.QRect(10, 200, 300, 50))
        self.publickey_4.setObjectName("publickey_4")
        self.verifysign_btn = QtWidgets.QPushButton(self.widget_center_4)
        self.verifysign_btn.setGeometry(QtCore.QRect(100, 270, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verifysign_btn.setFont(font)
        self.verifysign_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.verifysign_btn.setObjectName("verifysign_btn")
        self.verifyfile_btn = QtWidgets.QPushButton(self.widget_center_4)
        self.verifyfile_btn.setGeometry(QtCore.QRect(90, 100, 21, 21))
        self.verifyfile_btn.setStyleSheet("border-color: rgb(240, 255, 255);")
        self.verifyfile_btn.setText("")
        self.verifyfile_btn.setIcon(icon1)
        self.verifyfile_btn.setIconSize(QtCore.QSize(20, 20))
        self.verifyfile_btn.setObjectName("verifyfile_btn")
        self.signfile_btn = QtWidgets.QPushButton(self.widget_center_4)
        self.signfile_btn.setGeometry(QtCore.QRect(80, 180, 21, 21))
        self.signfile_btn.setStyleSheet("border-color: rgb(240, 255, 255);")
        self.signfile_btn.setText("")
        self.signfile_btn.setIcon(icon1)
        self.signfile_btn.setIconSize(QtCore.QSize(20, 20))
        self.signfile_btn.setObjectName("signfile_btn")
        self.widget_right = QtWidgets.QWidget(self.verify)
        self.widget_right.setGeometry(QtCore.QRect(360, 0, 351, 461))
        self.widget_right.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_right.setObjectName("widget_right")
        self.label_4 = QtWidgets.QLabel(self.widget_right)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.orisigner_uuid = QtWidgets.QTextBrowser(self.widget_right)
        self.orisigner_uuid.setGeometry(QtCore.QRect(10, 110, 321, 31))
        self.orisigner_uuid.setObjectName("orisigner_uuid")
        self.agent_uuid = QtWidgets.QLabel(self.widget_right)
        self.agent_uuid.setGeometry(QtCore.QRect(10, 150, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.agent_uuid.setFont(font)
        self.agent_uuid.setObjectName("agent_uuid")
        self.label_6 = QtWidgets.QLabel(self.widget_right)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 72, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_right)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.widget_right)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 170, 321, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.timestamp = QtWidgets.QTextBrowser(self.widget_right)
        self.timestamp.setGeometry(QtCore.QRect(10, 230, 321, 31))
        self.timestamp.setObjectName("timestamp")
        self.signeffective = QtWidgets.QTextBrowser(self.widget_right)
        self.signeffective.setGeometry(QtCore.QRect(10, 290, 321, 31))
        self.signeffective.setObjectName("signeffective")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./Resources/verify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoview.addTab(self.verify, icon3, "")
        self.proxy = QtWidgets.QWidget()
        self.proxy.setObjectName("proxy")
        self.widget_center_5 = QtWidgets.QWidget(self.proxy)
        self.widget_center_5.setGeometry(QtCore.QRect(20, 0, 341, 461))
        self.widget_center_5.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_center_5.setObjectName("widget_center_5")
        self.label_11 = QtWidgets.QLabel(self.widget_center_5)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_11.setObjectName("label_11")
        self.agentclient = QtWidgets.QComboBox(self.widget_center_5)
        self.agentclient.setGeometry(QtCore.QRect(10, 110, 301, 21))
        self.agentclient.setObjectName("agentclient")
        self.label_14 = QtWidgets.QLabel(self.widget_center_5)
        self.label_14.setGeometry(QtCore.QRect(10, 160, 71, 16))
        self.label_14.setObjectName("label_14")
        self.authorizelist = QtWidgets.QComboBox(self.widget_center_5)
        self.authorizelist.setGeometry(QtCore.QRect(10, 180, 301, 21))
        self.authorizelist.setObjectName("authorizelist")
        self.newproxy_btn = QtWidgets.QPushButton(self.widget_center_5)
        self.newproxy_btn.setGeometry(QtCore.QRect(90, 240, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.newproxy_btn.setFont(font)
        self.newproxy_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.newproxy_btn.setObjectName("newproxy_btn")
        self.widget_right_4 = QtWidgets.QWidget(self.proxy)
        self.widget_right_4.setGeometry(QtCore.QRect(360, 0, 351, 461))
        self.widget_right_4.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.widget_right_4.setObjectName("widget_right_4")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.widget_right_4)
        self.textBrowser_12.setGeometry(QtCore.QRect(40, 60, 291, 261))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.changeremark_btn = QtWidgets.QPushButton(self.widget_right_4)
        self.changeremark_btn.setGeometry(QtCore.QRect(120, 340, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.changeremark_btn.setFont(font)
        self.changeremark_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.changeremark_btn.setObjectName("changeremark_btn")
        self.cancleauthorize_btn = QtWidgets.QPushButton(self.widget_right_4)
        self.cancleauthorize_btn.setGeometry(QtCore.QRect(120, 380, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancleauthorize_btn.setFont(font)
        self.cancleauthorize_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.cancleauthorize_btn.setObjectName("cancleauthorize_btn")
        self.label_22 = QtWidgets.QLabel(self.widget_right_4)
        self.label_22.setGeometry(QtCore.QRect(50, 200, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.uuid = QtWidgets.QLabel(self.widget_right_4)
        self.uuid.setGeometry(QtCore.QRect(50, 70, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uuid.setFont(font)
        self.uuid.setObjectName("uuid")
        self.user_uuid = QtWidgets.QTextBrowser(self.widget_right_4)
        self.user_uuid.setGeometry(QtCore.QRect(50, 90, 261, 31))
        self.user_uuid.setObjectName("user_uuid")
        self.effective = QtWidgets.QTextBrowser(self.widget_right_4)
        self.effective.setGeometry(QtCore.QRect(50, 220, 261, 31))
        self.effective.setObjectName("effective")
        self.authorizetime = QtWidgets.QTextBrowser(self.widget_right_4)
        self.authorizetime.setGeometry(QtCore.QRect(50, 160, 261, 31))
        self.authorizetime.setObjectName("authorizetime")
        self.agent_uuid_3 = QtWidgets.QLabel(self.widget_right_4)
        self.agent_uuid_3.setGeometry(QtCore.QRect(50, 130, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.agent_uuid_3.setFont(font)
        self.agent_uuid_3.setObjectName("agent_uuid_3")
        self.label_23 = QtWidgets.QLabel(self.widget_right_4)
        self.label_23.setGeometry(QtCore.QRect(50, 260, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.withdrawtime = QtWidgets.QTextBrowser(self.widget_right_4)
        self.withdrawtime.setGeometry(QtCore.QRect(50, 280, 261, 31))
        self.withdrawtime.setObjectName("withdrawtime")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./Resources/proxy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoview.addTab(self.proxy, icon4, "")

        self.retranslateUi(infoview)
        infoview.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(infoview)

    def retranslateUi(self, infoview):
        _translate = QtCore.QCoreApplication.translate
        infoview.setWindowTitle(_translate("infoview", "TabWidget"))
        self.label_15.setText(_translate("infoview", "用户名（可编辑）"))
        self.label_16.setText(_translate("infoview", "UUID"))
        self.label_17.setText(_translate("infoview", "公钥"))
        self.reset_btn.setText(_translate("infoview", "重置密钥"))
        self.label_18.setText(_translate("infoview", "版本号："))
        self.label_19.setText(_translate("infoview", "作者："))
        self.label_20.setText(_translate("infoview", "工作目录："))
        self.label_21.setText(_translate("infoview", "其他信息："))
        self.new_btn.setText(_translate("infoview", "新建用户"))
        infoview.setTabText(infoview.indexOf(self.information), _translate("infoview", "信息"))
        self.label_8.setText(_translate("infoview", "签名人"))
        self.label_9.setText(_translate("infoview", "选择签名文件"))
        self.label_10.setText(_translate("infoview", "签名后文件"))
        self.excu_btn.setText(_translate("infoview", "执行签名"))
        infoview.setTabText(infoview.indexOf(self.signature), _translate("infoview", "签名"))
        self.label_12.setText(_translate("infoview", "校验文件名"))
        self.label_13.setText(_translate("infoview", "签名文件"))
        self.verifysign_btn.setText(_translate("infoview", "校验签名"))
        self.label_4.setText(_translate("infoview", "原签名人UUID:"))
        self.agent_uuid.setText(_translate("infoview", "代理人UUID:"))
        self.label_6.setText(_translate("infoview", "时间戳："))
        self.label_7.setText(_translate("infoview", "签名是否有效："))
        infoview.setTabText(infoview.indexOf(self.verify), _translate("infoview", "校验"))
        self.label_11.setText(_translate("infoview", "代理客户"))
        self.label_14.setText(_translate("infoview", "授权列表"))
        self.newproxy_btn.setText(_translate("infoview", "新建代理"))
        self.changeremark_btn.setText(_translate("infoview", "更改备注"))
        self.cancleauthorize_btn.setText(_translate("infoview", "撤销授权"))
        self.label_22.setText(_translate("infoview", "是否有效："))
        self.uuid.setText(_translate("infoview", "UUID:"))
        self.agent_uuid_3.setText(_translate("infoview", "授权时间："))
        self.label_23.setText(_translate("infoview", "注销时间："))
        infoview.setTabText(infoview.indexOf(self.proxy), _translate("infoview", "代理"))